"""Analytics schemas"""

from app.schemas.analytics.performance import (
    PerformanceBase,
    PerformanceCreate,
    PerformanceUpdate,
    PerformanceResponse,
    PerformanceList,
    PerformanceStats,
    TopPerformer,
    PerformanceTrend,
    CourierComparison,
    DateRangeQuery,
    PerformanceBulkCreate,
)

from app.schemas.analytics.common import (
    PeriodType,
    ComparisonType,
    TrendDirection,
    PerformanceCategory,
    DateRangeParams,
    MetricValue,
    TrendDataPoint,
    ComparisonData,
    KPICard,
    ChartData,
    TopPerformerItem,
    DistributionBucket,
    AlertItem,
    ExportRequest,
    PaginationParams,
    PaginatedResponse,
)

__all__ = [
    # Performance schemas
    "PerformanceBase",
    "PerformanceCreate",
    "PerformanceUpdate",
    "PerformanceResponse",
    "PerformanceList",
    "PerformanceStats",
    "TopPerformer",
    "PerformanceTrend",
    "CourierComparison",
    "DateRangeQuery",
    "PerformanceBulkCreate",
    # Common analytics schemas
    "PeriodType",
    "ComparisonType",
    "TrendDirection",
    "PerformanceCategory",
    "DateRangeParams",
    "MetricValue",
    "TrendDataPoint",
    "ComparisonData",
    "KPICard",
    "ChartData",
    "TopPerformerItem",
    "DistributionBucket",
    "AlertItem",
    "ExportRequest",
    "PaginationParams",
    "PaginatedResponse",
]
