"""
Test Utilities Package for BARQ Fleet Management System

This package provides comprehensive utilities for testing including:
- Data factories (factories.py)
- API test helpers (api_helpers.py)
- Mock utilities (mocks.py)
- Test helpers (test_helpers.py)

Author: BARQ QA Team
Last Updated: 2025-12-02
"""

from .factories import (
    UserFactory,
    AdminUserFactory,
    ManagerUserFactory,
    CourierFactory,
    VehicleFactory,
    AssignmentFactory,
    MaintenanceFactory,
    FuelLogFactory,
    LeaveFactory,
    LoanFactory,
    SalaryFactory,
    AttendanceFactory,
    BonusFactory,
    DeliveryFactory,
    CODCollectionFactory,
    RouteFactory,
    IncidentFactory,
    TicketFactory,
    WorkflowTemplateFactory,
    WorkflowInstanceFactory,
    create_courier_with_salary,
    create_vehicle_assignment,
    create_delivery_workflow,
    create_leave_request_workflow,
)

from .api_helpers import (
    get_auth_headers,
    create_test_token,
    login_user,
    make_get_request,
    make_post_request,
    make_put_request,
    make_patch_request,
    make_delete_request,
    assert_success_response,
    assert_error_response,
    assert_validation_error,
    assert_unauthorized,
    assert_forbidden,
    assert_not_found,
    assert_courier_data,
    assert_vehicle_data,
    assert_delivery_data,
    assert_pagination,
    test_list_endpoint,
    test_filter_endpoint,
    test_search_endpoint,
    test_create_endpoint,
    test_get_endpoint,
    test_update_endpoint,
    test_delete_endpoint,
    create_workflow_instance,
    approve_workflow_step,
    reject_workflow_step,
)

__all__ = [
    # Factories
    "UserFactory",
    "AdminUserFactory",
    "ManagerUserFactory",
    "CourierFactory",
    "VehicleFactory",
    "AssignmentFactory",
    "MaintenanceFactory",
    "FuelLogFactory",
    "LeaveFactory",
    "LoanFactory",
    "SalaryFactory",
    "AttendanceFactory",
    "BonusFactory",
    "DeliveryFactory",
    "CODCollectionFactory",
    "RouteFactory",
    "IncidentFactory",
    "TicketFactory",
    "WorkflowTemplateFactory",
    "WorkflowInstanceFactory",
    "create_courier_with_salary",
    "create_vehicle_assignment",
    "create_delivery_workflow",
    "create_leave_request_workflow",
    # API Helpers
    "get_auth_headers",
    "create_test_token",
    "login_user",
    "make_get_request",
    "make_post_request",
    "make_put_request",
    "make_patch_request",
    "make_delete_request",
    "assert_success_response",
    "assert_error_response",
    "assert_validation_error",
    "assert_unauthorized",
    "assert_forbidden",
    "assert_not_found",
    "assert_courier_data",
    "assert_vehicle_data",
    "assert_delivery_data",
    "assert_pagination",
    "test_list_endpoint",
    "test_filter_endpoint",
    "test_search_endpoint",
    "test_create_endpoint",
    "test_get_endpoint",
    "test_update_endpoint",
    "test_delete_endpoint",
    "create_workflow_instance",
    "approve_workflow_step",
    "reject_workflow_step",
]
