# Google Cloud Build Configuration for BARQ Fleet Management
# OPTIMIZED for faster builds - parallel execution maximized

substitutions:
  _REGION: me-central1
  _REPOSITORY: barq-fleet
  _SERVICE_BACKEND: barq-api
  _SERVICE_FRONTEND: barq-web
  _TAG: latest

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true
  substitution_option: 'ALLOW_LOOSE'

timeout: 1800s  # 30 minutes (reduced from 60)

steps:
  # ==============================================================================
  # PHASE 1: Install Dependencies (PARALLEL)
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/npm'
    id: 'install-frontend-deps'
    dir: 'frontend'
    args: ['ci', '--prefer-offline', '--no-audit']
    waitFor: ['-']

  # ==============================================================================
  # PHASE 2: Lint + Type Check + Build Frontend (PARALLEL with backend)
  # Run lint/typecheck while building - don't wait for tests
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/npm'
    id: 'frontend-checks-and-build'
    dir: 'frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm run lint &
        npm run type-check &
        wait
        npm run build
    env:
      - 'VITE_API_URL=https://${_SERVICE_BACKEND}-staging-${PROJECT_NUMBER}.${_REGION}.run.app/api/v1'
      - 'NODE_ENV=production'
    waitFor: ['install-frontend-deps']

  # ==============================================================================
  # PHASE 2: Build Docker Images (PARALLEL - start early)
  # Backend image can start building immediately - only needs source code
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend-image'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_BACKEND}:${_TAG}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_BACKEND}:latest'
      - '-f'
      - './backend/Dockerfile.prod'
      - '--cache-from'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_BACKEND}:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - './backend'
    waitFor: ['-']  # Start immediately!

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend-image'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_FRONTEND}:${_TAG}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_FRONTEND}:latest'
      - '-f'
      - './frontend/Dockerfile.prod'
      - '--cache-from'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_FRONTEND}:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - './frontend'
    waitFor: ['frontend-checks-and-build']

  # ==============================================================================
  # PHASE 3: Push Images (PARALLEL - as soon as each image is ready)
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend-image'
    args: ['push', '--all-tags', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_BACKEND}']
    waitFor: ['build-backend-image']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend-image'
    args: ['push', '--all-tags', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_FRONTEND}']
    waitFor: ['build-frontend-image']

  # ==============================================================================
  # PHASE 4: Deploy (PARALLEL - as soon as each image is pushed)
  # ==============================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend-staging'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_BACKEND}-staging'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_BACKEND}:${_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'ENVIRONMENT=staging,POSTGRES_USER=postgres,POSTGRES_DB=barq_fleet,UPSTASH_REDIS_REST_URL=https://fine-lobster-35915.upstash.io'
      - '--set-secrets'
      - 'SECRET_KEY=barq-secret-key:latest,POSTGRES_PASSWORD=barq-postgres-password:latest,UPSTASH_REDIS_REST_TOKEN=upstash-redis-token:latest'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--cpu'
      - '2'
      - '--memory'
      - '2Gi'
      - '--timeout'
      - '300s'
    waitFor: ['push-backend-image']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend-staging'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_FRONTEND}-staging'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_FRONTEND}:${_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '5'
      - '--cpu'
      - '1'
      - '--memory'
      - '512Mi'
    waitFor: ['push-frontend-image']

  # ==============================================================================
  # PHASE 5: Verification (PARALLEL smoke tests)
  # ==============================================================================
  - name: 'curlimages/curl:latest'
    id: 'smoke-test'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Waiting for services to be ready..."
        sleep 10
        curl -sf --retry 3 --retry-delay 5 "https://${_SERVICE_BACKEND}-staging-${PROJECT_NUMBER}.${_REGION}.run.app/api/v1/health" && echo "Backend OK" || echo "Backend check failed"
        curl -sf --retry 3 --retry-delay 5 "https://${_SERVICE_FRONTEND}-staging-${PROJECT_NUMBER}.${_REGION}.run.app/" && echo "Frontend OK" || echo "Frontend check failed"
        echo "Deployment complete!"
    waitFor: ['deploy-backend-staging', 'deploy-frontend-staging']
    allowFailure: true

# Images to be pushed to Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_BACKEND}:${_TAG}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_BACKEND}:latest'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_FRONTEND}:${_TAG}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_FRONTEND}:latest'
