# Cloud Build configuration for running database migrations
# Run with: gcloud builds submit --config=cloudbuild.migrate.yaml --project=barqdps .
#
# This uses the Cloud SQL Proxy to connect to the production database and run Alembic migrations.

substitutions:
  _CLOUD_SQL_INSTANCE: barqdps:me-central1:barq-postgres-staging

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 600s  # 10 minutes

steps:
  # Step 1: Build backend image with all dependencies (if not already built)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args:
      - 'build'
      - '-t'
      - 'migration-runner'
      - '-f'
      - './backend/Dockerfile.prod'
      - './backend'
    waitFor: ['-']

  # Step 2: Run Alembic migrations using Cloud SQL Proxy sidecar approach
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'run-migrations'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "=== Starting Cloud SQL Proxy ==="

        # Install cloud-sql-proxy
        curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.8.0/cloud-sql-proxy.linux.amd64
        chmod +x cloud-sql-proxy

        # Start proxy in background
        mkdir -p /cloudsql
        ./cloud-sql-proxy --unix-socket /cloudsql ${_CLOUD_SQL_INSTANCE} &
        PROXY_PID=$$!

        # Wait for proxy to be ready
        sleep 5
        echo "Cloud SQL Proxy started with PID $$PROXY_PID"

        # Get password from Secret Manager
        export POSTGRES_PASSWORD=$(gcloud secrets versions access latest --secret=barq-postgres-password)

        echo "=== Installing Python dependencies ==="
        apt-get update -qq && apt-get install -y -qq python3 python3-pip python3-venv > /dev/null 2>&1

        cd backend
        python3 -m venv /tmp/venv
        source /tmp/venv/bin/activate
        pip install --quiet alembic sqlalchemy psycopg2-binary pydantic pydantic-settings python-jose argon2-cffi

        echo "=== Checking current migration status ==="
        export POSTGRES_USER=postgres
        export POSTGRES_DB=barq_fleet
        export POSTGRES_SERVER=/cloudsql/${_CLOUD_SQL_INSTANCE}

        alembic current || echo "No migrations applied yet"

        echo "=== Running migrations ==="
        alembic upgrade head

        echo "=== Migration status after upgrade ==="
        alembic current

        echo "=== Migrations complete! ==="

        # Cleanup
        kill $$PROXY_PID 2>/dev/null || true
    waitFor: ['build-backend']
