# Google Cloud Build Configuration for SYNC Fleet Management
# ============================================================================
# SINGLE SOURCE OF TRUTH - ALL CONFIGURATION AND SECRETS
# ============================================================================

substitutions:
  # ==========================================================================
  # CONFIGURATION (secrets stored in Google Secret Manager)
  # ==========================================================================

  # Infrastructure
  _REGION: me-central1
  _REPOSITORY: barq-fleet
  _SERVICE_BACKEND: sync-api
  _SERVICE_FRONTEND: sync-web
  _TAG: latest
  _CLOUD_SQL_INSTANCE: barqdps:me-central1:barq-postgres-staging

  # Database
  _POSTGRES_USER: postgres
  _POSTGRES_DB: barq_fleet

  # URLs (non-sensitive)
  _UPSTASH_REDIS_URL: 'https://fine-lobster-35915.upstash.io'
  _SYARAH_API_URL: 'https://sydashboard.syarahapp.sa'
  _SYARAH_BRANCH_IDS: '1071'
  _SYARAH_SYNC_INTERVAL_MINUTES: '5'
  _FMS_BASE_URL: 'https://fms-api.machinestalk.com/fmsv2'
  _FMS_TIMEOUT: '30'

  # Frontend build-time variables (public/non-sensitive)
  _VITE_GOOGLE_CLIENT_ID: '869422381378-9sonvj1dnjoh465826dcjrn4jo9r0hon.apps.googleusercontent.com'
  _VITE_SENTRY_DSN: 'https://1d4a11dd37b450b94c2cd5ab0af41214@o4509510591971328.ingest.us.sentry.io/4510504846950400'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true
  substitution_option: 'ALLOW_LOOSE'

timeout: 1800s  # 30 minutes

steps:
  # ==============================================================================
  # PHASE 1: Install Dependencies (PARALLEL)
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/npm'
    id: 'install-frontend-deps'
    dir: 'frontend'
    args: ['ci', '--prefer-offline', '--no-audit']
    waitFor: ['-']

  # ==============================================================================
  # PHASE 2: Lint + Type Check + Build Frontend (PARALLEL with backend)
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/npm'
    id: 'frontend-checks-and-build'
    dir: 'frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm run lint &
        npm run type-check &
        wait
        npm run build
    env:
      - 'VITE_API_URL=https://${_SERVICE_BACKEND}-${PROJECT_NUMBER}.${_REGION}.run.app/api/v1'
      - 'NODE_ENV=production'
      - 'VITE_GOOGLE_CLIENT_ID=${_VITE_GOOGLE_CLIENT_ID}'
      - 'VITE_SENTRY_DSN=${_VITE_SENTRY_DSN}'
    waitFor: ['install-frontend-deps']

  # ==============================================================================
  # PHASE 2: Build Docker Images (PARALLEL - start early)
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend-image'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/barq-api:${_TAG}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/barq-api:latest'
      - '-f'
      - './backend/Dockerfile.prod'
      - '--cache-from'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/barq-api:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - './backend'
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend-image'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/barq-web:${_TAG}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/barq-web:latest'
      - '-f'
      - './frontend/Dockerfile.prod'
      - '--cache-from'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/barq-web:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - './frontend'
    waitFor: ['frontend-checks-and-build']

  # ==============================================================================
  # PHASE 3: Push Images (PARALLEL)
  # ==============================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend-image'
    args: ['push', '--all-tags', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/barq-api']
    waitFor: ['build-backend-image']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend-image'
    args: ['push', '--all-tags', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/barq-web']
    waitFor: ['build-frontend-image']

  # ==============================================================================
  # PHASE 4: Deploy to Production (with Cloud SQL)
  # ==============================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_BACKEND}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/barq-api:${_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '${_CLOUD_SQL_INSTANCE}'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,POSTGRES_USER=${_POSTGRES_USER},POSTGRES_DB=${_POSTGRES_DB},POSTGRES_SERVER=/cloudsql/${_CLOUD_SQL_INSTANCE},UPSTASH_REDIS_REST_URL=${_UPSTASH_REDIS_URL},SYARAH_API_URL=${_SYARAH_API_URL},SYARAH_BRANCH_IDS=${_SYARAH_BRANCH_IDS},SYARAH_SYNC_INTERVAL_MINUTES=${_SYARAH_SYNC_INTERVAL_MINUTES},FMS_BASE_URL=${_FMS_BASE_URL},FMS_TIMEOUT=${_FMS_TIMEOUT},BACKEND_CORS_ORIGINS=https://${_SERVICE_FRONTEND}-${PROJECT_NUMBER}.${_REGION}.run.app'
      - '--set-secrets'
      - 'SECRET_KEY=barq-secret-key:latest,POSTGRES_PASSWORD=barq-postgres-password:latest,GOOGLE_CLIENT_ID=barq-google-client-id:latest,GOOGLE_CLIENT_SECRET=barq-google-client-secret:latest,UPSTASH_REDIS_REST_TOKEN=upstash-redis-token:latest,SYARAH_USERNAME=syarah-username:latest,SYARAH_PASSWORD=syarah-password:latest,FMS_USERNAME=fms-username:latest,FMS_PASSWORD=fms-password:latest,SENTRY_DSN=sentry-dsn-backend:latest'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '50'
      - '--cpu'
      - '2'
      - '--memory'
      - '2Gi'
      - '--timeout'
      - '300s'
      - '--concurrency'
      - '100'
    waitFor: ['push-backend-image']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_FRONTEND}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/barq-web:${_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '20'
      - '--cpu'
      - '1'
      - '--memory'
      - '512Mi'
    waitFor: ['push-frontend-image']

  # ==============================================================================
  # PHASE 5: Verification (smoke tests)
  # ==============================================================================
  - name: 'curlimages/curl:latest'
    id: 'smoke-test'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Waiting for services to be ready..."
        sleep 15
        curl -sf --retry 5 --retry-delay 5 "https://${_SERVICE_BACKEND}-${PROJECT_NUMBER}.${_REGION}.run.app/health" && echo "Backend OK" || echo "Backend check failed"
        curl -sf --retry 5 --retry-delay 5 "https://${_SERVICE_FRONTEND}-${PROJECT_NUMBER}.${_REGION}.run.app/" && echo "Frontend OK" || echo "Frontend check failed"
        echo "Deployment complete!"
    waitFor: ['deploy-backend', 'deploy-frontend']
    allowFailure: true

# Images to be pushed to Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/barq-api:${_TAG}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/barq-api:latest'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/barq-web:${_TAG}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/barq-web:latest'

